repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: e84319e627902e1b348574ecf3238dc511933dc7  # frozen: v0.11.7
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 62328b73a901c7bfa2f8cd2985a3ce435cafc378  # frozen: 0.6.17
    hooks:
      - id: uv-lock
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
