repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 3d44372123ca5e8617fdb65d9f11facd159b9e95  # frozen: v0.12.3
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 4b94be130f0326b2abddb9cade8248eb4b0fdadb  # frozen: 0.7.20
    hooks:
      - id: uv-lock
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
